<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Excelファイルの読み込み | index.split</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Excelファイルの読み込み | index.split" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Excelファイルの読み込み | index.split" />
  
  
  <meta name="twitter:image" content="images/cover.png" />




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="project.html"/>
<link rel="next" href="writeexcel.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>はじめに</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#本書の特徴"><i class="fa fa-check"></i>本書の特徴</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#想定読者"><i class="fa fa-check"></i>想定読者</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure"><i class="fa fa-check"></i>本書の構成</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#執筆環境"><i class="fa fa-check"></i>執筆環境</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#注意事項など"><i class="fa fa-check"></i>注意事項など</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#huroku"><i class="fa fa-check"></i>特別付録について</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="project.html"><a href="project.html"><i class="fa fa-check"></i><b>1</b> 前提：プロジェクトの設定</a><ul>
<li class="chapter" data-level="1.1" data-path="project.html"><a href="project.html#どのフォルダのファイルかの指定"><i class="fa fa-check"></i><b>1.1</b> どのフォルダのファイルかの指定</a></li>
<li class="chapter" data-level="1.2" data-path="project.html"><a href="project.html#projecttoha"><i class="fa fa-check"></i><b>1.2</b> プロジェクトとは</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="readexcel.html"><a href="readexcel.html"><i class="fa fa-check"></i><b>2</b> Excelファイルの読み込み</a><ul>
<li class="chapter" data-level="2.1" data-path="readexcel.html"><a href="readexcel.html#readoneexcel"><i class="fa fa-check"></i><b>2.1</b> 一つのExcelファイルを読み込む</a><ul>
<li class="chapter" data-level="2.1.1" data-path="readexcel.html"><a href="readexcel.html#junbiyomikomi"><i class="fa fa-check"></i><b>2.1.1</b> ファイルの準備と読み込み</a></li>
<li class="chapter" data-level="2.1.2" data-path="readexcel.html"><a href="readexcel.html#列名変数名がひどい場合の読み込み"><i class="fa fa-check"></i><b>2.1.2</b> 列名（変数名）がひどい場合の読み込み</a></li>
<li class="chapter" data-level="2.1.3" data-path="readexcel.html"><a href="readexcel.html#開始行を指定して読み込む"><i class="fa fa-check"></i><b>2.1.3</b> 開始行を指定して読み込む</a></li>
<li class="chapter" data-level="2.1.4" data-path="readexcel.html"><a href="readexcel.html#セルを指定して読み込む"><i class="fa fa-check"></i><b>2.1.4</b> セルを指定して読み込む</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="readexcel.html"><a href="readexcel.html#シートを指定して読み込む"><i class="fa fa-check"></i><b>2.2</b> シートを指定して読み込む</a><ul>
<li class="chapter" data-level="2.2.1" data-path="readexcel.html"><a href="readexcel.html#シート名の確認"><i class="fa fa-check"></i><b>2.2.1</b> シート名の確認</a></li>
<li class="chapter" data-level="2.2.2" data-path="readexcel.html"><a href="readexcel.html#普通の読み込み"><i class="fa fa-check"></i><b>2.2.2</b> 普通の読み込み</a></li>
<li class="chapter" data-level="2.2.3" data-path="readexcel.html"><a href="readexcel.html#シートを指定した読み込み"><i class="fa fa-check"></i><b>2.2.3</b> シートを指定した読み込み</a></li>
<li class="chapter" data-level="2.2.4" data-path="readexcel.html"><a href="readexcel.html#dflist"><i class="fa fa-check"></i><b>2.2.4</b> すべてのシートから一気に読み込み</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="readexcel.html"><a href="readexcel.html#readseveralexcel"><i class="fa fa-check"></i><b>2.3</b> 複数のExcelファイルを読み込む</a><ul>
<li class="chapter" data-level="2.3.1" data-path="readexcel.html"><a href="readexcel.html#読み込むファイル名の一覧のオブジェクト作成"><i class="fa fa-check"></i><b>2.3.1</b> 読み込むファイル名の一覧のオブジェクト作成</a></li>
<li class="chapter" data-level="2.3.2" data-path="readexcel.html"><a href="readexcel.html#ikkatsuread"><i class="fa fa-check"></i><b>2.3.2</b> ファイルを一括で読み込む</a></li>
<li class="chapter" data-level="2.3.3" data-path="readexcel.html"><a href="readexcel.html#読み込むファイルが複数フォルダにある場合"><i class="fa fa-check"></i><b>2.3.3</b> 読み込むファイルが複数フォルダにある場合</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="writeexcel.html"><a href="writeexcel.html"><i class="fa fa-check"></i><b>3</b> Excelファイルの保存</a><ul>
<li class="chapter" data-level="3.1" data-path="writeexcel.html"><a href="writeexcel.html#writeoneexcel"><i class="fa fa-check"></i><b>3.1</b> 一つのExcelファイルを保存する</a><ul>
<li class="chapter" data-level="3.1.1" data-path="writeexcel.html"><a href="writeexcel.html#groupbymean"><i class="fa fa-check"></i><b>3.1.1</b> カテゴリ別平均値の作成</a></li>
<li class="chapter" data-level="3.1.2" data-path="writeexcel.html"><a href="writeexcel.html#excelファイルの保存"><i class="fa fa-check"></i><b>3.1.2</b> Excelファイルの保存</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="writeexcel.html"><a href="writeexcel.html#writeseveralexcel"><i class="fa fa-check"></i><b>3.2</b> 複数のファイルを一度に保存する</a><ul>
<li class="chapter" data-level="3.2.1" data-path="writeexcel.html"><a href="writeexcel.html#splitdf"><i class="fa fa-check"></i><b>3.2.1</b> データフレームをカテゴリ別に分割してリストにする</a></li>
<li class="chapter" data-level="3.2.2" data-path="writeexcel.html"><a href="writeexcel.html#リストの各要素を個別でexcelファイルに保存する"><i class="fa fa-check"></i><b>3.2.2</b> リストの各要素を個別でExcelファイルに保存する</a></li>
<li class="chapter" data-level="3.2.3" data-path="writeexcel.html"><a href="writeexcel.html#一つのファイルの複数シートに保存する"><i class="fa fa-check"></i><b>3.2.3</b> 一つのファイルの複数シートに保存する</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="readsavecsv.html"><a href="readsavecsv.html"><i class="fa fa-check"></i><b>4</b> csvファイルの読み込みと保存</a><ul>
<li class="chapter" data-level="4.1" data-path="readsavecsv.html"><a href="readsavecsv.html#一つのcsvファイルを読み込む"><i class="fa fa-check"></i><b>4.1</b> 一つのcsvファイルを読み込む</a><ul>
<li class="chapter" data-level="4.1.1" data-path="readsavecsv.html"><a href="readsavecsv.html#utf-8でエンコードされたcsvファイル"><i class="fa fa-check"></i><b>4.1.1</b> UTF-8でエンコードされたcsvファイル</a></li>
<li class="chapter" data-level="4.1.2" data-path="readsavecsv.html"><a href="readsavecsv.html#文字化けの例shift-jisでエンコードされたcsvファイル"><i class="fa fa-check"></i><b>4.1.2</b> 【文字化けの例】Shift-JISでエンコードされたcsvファイル</a></li>
<li class="chapter" data-level="4.1.3" data-path="readsavecsv.html"><a href="readsavecsv.html#shift-jisでエンコードされたcsvファイル"><i class="fa fa-check"></i><b>4.1.3</b> Shift-JISでエンコードされたcsvファイル</a></li>
<li class="chapter" data-level="4.1.4" data-path="readsavecsv.html"><a href="readsavecsv.html#read.csvを使う場合"><i class="fa fa-check"></i><b>4.1.4</b> read.csv()を使う場合</a></li>
<li class="chapter" data-level="4.1.5" data-path="readsavecsv.html"><a href="readsavecsv.html#大きいデータならfread"><i class="fa fa-check"></i><b>4.1.5</b> 大きいデータならfread()</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="readsavecsv.html"><a href="readsavecsv.html#writeonecsv"><i class="fa fa-check"></i><b>4.2</b> csvファイルの保存</a><ul>
<li class="chapter" data-level="4.2.1" data-path="readsavecsv.html"><a href="readsavecsv.html#write_csvを使う"><i class="fa fa-check"></i><b>4.2.1</b> write_csv()を使う</a></li>
<li class="chapter" data-level="4.2.2" data-path="readsavecsv.html"><a href="readsavecsv.html#write.csvを使う"><i class="fa fa-check"></i><b>4.2.2</b> write.csv()を使う</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataanal.html"><a href="dataanal.html"><i class="fa fa-check"></i><b>5</b> データ解析に向けて</a><ul>
<li class="chapter" data-level="5.1" data-path="dataanal.html"><a href="dataanal.html#要約値や欠損データの確認"><i class="fa fa-check"></i><b>5.1</b> 要約値や欠損データの確認</a><ul>
<li class="chapter" data-level="5.1.1" data-path="dataanal.html"><a href="dataanal.html#結果をexcelファイルに出力する"><i class="fa fa-check"></i><b>5.1.1</b> 結果をExcelファイルに出力する</a></li>
<li class="chapter" data-level="5.1.2" data-path="dataanal.html"><a href="dataanal.html#可視化"><i class="fa fa-check"></i><b>5.1.2</b> 可視化</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dataanal.html"><a href="dataanal.html#相関の確認"><i class="fa fa-check"></i><b>5.2</b> 相関の確認</a><ul>
<li class="chapter" data-level="5.2.1" data-path="dataanal.html"><a href="dataanal.html#相関行列を出す"><i class="fa fa-check"></i><b>5.2.1</b> 相関行列を出す</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataanal.html"><a href="dataanal.html#相関行列の可視化"><i class="fa fa-check"></i><b>5.2.2</b> 相関行列の可視化</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="あとがき.html"><a href="あとがき.html"><i class="fa fa-check"></i>あとがき</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="readexcel" class="section level1">
<h1><span class="header-section-number">2</span> Excelファイルの読み込み</h1>
<div id="readoneexcel" class="section level2">
<h2><span class="header-section-number">2.1</span> 一つのExcelファイルを読み込む</h2>
<div id="junbiyomikomi" class="section level3">
<h3><span class="header-section-number">2.1.1</span> ファイルの準備と読み込み</h3>
<p>ExcelファイルをRに読み込むには、<code>readxl</code>パッケージが便利です。<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>セクション<a href="project.html#projecttoha">1.2</a>で述べた通り、ここからは、githubレポジトリのhttps://github.com/izunyan/excel_r をダウンロードしてプロジェクトを開いて進めてみてください。dataフォルダ（<code>data/</code>で表現）に入っている「ペンギン.xlsx」<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a>を読み込んでみましょう。</p>
<p>読み込みには<code>read_xlsx()</code>関数を使います。したがって、以下すべてExcelファイル形式は<code>.xlsx</code>を想定します。<code>read_xls()</code>や<code>read_excel()</code>という関数もあるので、ファイル形式によって使い分けられます。ファイル形式が混ざっている時は<code>read_excel()</code>が有用かもしれません。</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="readexcel.html#cb1-1"></a><span class="kw">library</span>(readxl)</span>
<span id="cb1-2"><a href="readexcel.html#cb1-2"></a></span>
<span id="cb1-3"><a href="readexcel.html#cb1-3"></a>df &lt;-<span class="st"> </span></span>
<span id="cb1-4"><a href="readexcel.html#cb1-4"></a><span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン.xlsx&quot;</span>) <span class="co"># Excelファイルの読み込み</span></span>
<span id="cb1-5"><a href="readexcel.html#cb1-5"></a></span>
<span id="cb1-6"><a href="readexcel.html#cb1-6"></a>df <span class="co"># データの表示 </span></span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Adelie  アデリー~ Torge~           39.1          18.7
## 2 Adelie  アデリー~ Torge~           39.5          17.4
## 3 Adelie  アデリー~ Torge~           40.3          18  
## # ... with 341 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
<p>上記コードを実行すると、RStudioの右上（デフォルトの配置であれば）のEnvironmentタブに、</p>
<pre><code>df  344 obs. of 9 variables</code></pre>
<p>という表示が出ると思います。つまり、344行のデータと9列の変数が入っているデータを、<code>df</code>という名前のもの（オブジェクト）としてRに読みこんだ、ということを示しています。<code>df &lt;-</code>の部分がその作業に該当します。<code>&lt;-</code>の右側の内容を左側のオブジェクトに格納するという意味です。ここで読み込まれた形がデータフレーム（<a href="index.html#structure">はじめに&gt;本書の構成</a>の注参照）です。</p>
<p>オブジェクト名である<code>df</code>と打つことで、デフォルトでは最初の10行分のデータが表示されます。ここでは紙面の都合で設定を変えているので3行だけにしています。表示された最初の行にも、<code>A tibble: 344 x 9</code>と、行数x列数の情報が出ています。表示しきれなかった行は、<code>with 341 more rows</code>と省略され、表示しきれなかった列は、<code>flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;, year &lt;dbl&gt;</code>と、<code>名前&lt;データの型名&gt;</code>が表示されます。なお、読みこんだファイルの保存については<a href="writeexcel.html#writeoneexcel">3.1</a>章で解説します。</p>
<div id="hokan" class="section level4">
<h4><span class="header-section-number">2.1.1.1</span> 最高な機能だよ！パスの自動補完</h4>
<p><code>read_xlsx("")</code>と打った後に、<code>" "</code>の中にカーソルを置いて、tabキーを押すと、プロジェクトの中身が一覧で表示されるので、選んでいくだけで目的のファイルがキーボードを打つことなしに選べます！RStudioは<code>" "</code>と打てばどこでもこの補完が可能です。<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a></p>
<p>上の階層のフォルダに行きたいときは、<code>" "</code>の中に<code>../</code>と打てば可能です。その後にtabキーを押せば上の階層のフォルダが選べます。</p>
</div>
</div>
<div id="列名変数名がひどい場合の読み込み" class="section level3">
<h3><span class="header-section-number">2.1.2</span> 列名（変数名）がひどい場合の読み込み</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="readexcel.html#cb4-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   Sｐｅｃｉｅｓ `種　類` `※島の名前` `①クチバシ　長さ（ｍｍ）`~
##   &lt;chr&gt;         &lt;chr&gt;    &lt;chr&gt;                  &lt;dbl&gt;
## 1 Adelie        アデリー Torgersen               39.1
## 2 Adelie        アデリー Torgersen               39.5
## 3 Adelie        アデリー Torgersen               40.3
## # ... with 341 more rows, and 5 more variables:
## #   `②ｸﾁﾊﾞｼ＿大きさ（ｍｍ）` &lt;dbl&gt;, `翼：長さ(mm)` &lt;dbl&gt;,
## #   `■体重　単位はｇ` &lt;dbl&gt;, `&lt;U+329B&gt;&lt;U+329A&gt;` &lt;chr&gt;,
## #   `２００７～２００９` &lt;dbl&gt;</code></pre>
<p>読めることは読めますが、今後のデータ処理を進めるうえで不安が残ります。</p>
<div id="スペースや記号などを自動的に変換してくれる関数できれいに" class="section level4">
<h4><span class="header-section-number">2.1.2.1</span> スペースや記号などを自動的に変換してくれる関数できれいに</h4>
<p><code>janitor</code>パッケージの<code>clean_names()</code>関数を使って、列名に入り込んでいるスペースや記号などを安全な記号に変換します。</p>
<p>なお、日本語の列名では、<code>clean_names()</code>関数に<code>case = "old_janitor"</code>をつけないと読みにくい結果になります。このように、関数の中に追加する情報のことを引数（ひきすう）と言います。引数によってさまざまな条件を変更することが可能になります。</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="readexcel.html#cb6-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb6-2"><a href="readexcel.html#cb6-2"></a>    <span class="co"># ↑は普通まず最初に読み込むパッケージですが、本書ではここで初めて使います</span></span>
<span id="cb6-3"><a href="readexcel.html#cb6-3"></a><span class="kw">library</span>(janitor)</span>
<span id="cb6-4"><a href="readexcel.html#cb6-4"></a></span>
<span id="cb6-5"><a href="readexcel.html#cb6-5"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb6-6"><a href="readexcel.html#cb6-6"></a><span class="st">  </span><span class="kw">clean_names</span>(<span class="dt">case =</span> <span class="st">&quot;old_janitor&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   sｐｅｃｉｅｓ 種_類 x_島の名前 x_クチバシ_長さ_ｍｍ~
##   &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt;                 &lt;dbl&gt;
## 1 Adelie        アデリー~ Torgersen              39.1
## 2 Adelie        アデリー~ Torgersen              39.5
## 3 Adelie        アデリー~ Torgersen              40.3
## # ... with 341 more rows, and 5 more variables:
## #   x_ｸﾁﾊﾞｼ_大きさ_ｍｍ &lt;dbl&gt;, 翼_長さ_mm &lt;dbl&gt;,
## #   x_体重_単位はｇ &lt;dbl&gt;, x_u_329b_u_329a &lt;chr&gt;,
## #   ２００７_２００９ &lt;dbl&gt;</code></pre>
<p>さて、ここで使われている <code>%&gt;%</code> は非常に大事なので解説しておきます。</p>
</div>
<div id="pipe" class="section level4">
<h4><span class="header-section-number">2.1.2.2</span> %&gt;% とは？</h4>
<p>「パイプ」と読みます。処理を重ねてコードに書いていきたい際に重宝し、現代の<code>tidyverse</code>を使ったRのコードに欠かせないものです。たとえば、データフレームdfのspecies列を選択する、という処理の</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="readexcel.html#cb8-1"></a><span class="kw">select</span>(df, species)</span></code></pre></div>
<p>は</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="readexcel.html#cb9-1"></a>df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(species)</span></code></pre></div>
<p>と書けます。 <code>%&gt;%</code>の左側にあるものを右側の最初の部分（第1引数）に渡すという働きです。パイプの利点は、いくつもつないで書いていけることです。たとえば、ペンギンの種類別にクチバシの長さの平均値を出したいときには次のようにできます。</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="readexcel.html#cb10-1"></a>df <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-2"><a href="readexcel.html#cb10-2"></a><span class="st">  </span><span class="kw">group_by</span>(species) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-3"><a href="readexcel.html#cb10-3"></a><span class="st">  </span><span class="kw">summarise</span>(平均値 =<span class="st"> </span><span class="kw">mean</span>(bill_length_mm, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   species   平均値
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Adelie      38.8
## 2 Chinstrap   48.8
## 3 Gentoo      47.5</code></pre>
<p>以下では<code>%&gt;%</code>を多用していきます。</p>
<p>なお、ショートカット<code>ctrl + shit + M</code>（Macだと<code>Cmd + Shift + M</code>）で出せます。</p>
</div>
<div id="全角半角を自動で" class="section level4">
<h4><span class="header-section-number">2.1.2.3</span> 全角←→半角を自動で</h4>
<p><code>stringi</code>パッケージの<code>stri_trans_nfkc()</code>関数を使って、変数名で全角-半角のばらつきを統一させます。</p>
<p>ここでは、変数名をリネームするのに<code>dplyr 1.0.0</code>で登場した<code>rename_with()</code>関数を使いました。<code>everything()</code>という引数を含めているので、すべての変数に対し、全角文字を含んでいたら半角に直すというコードになります。</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="readexcel.html#cb12-1"></a><span class="kw">library</span>(stringi)</span>
<span id="cb12-2"><a href="readexcel.html#cb12-2"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-3"><a href="readexcel.html#cb12-3"></a><span class="st">  </span><span class="kw">rename_with</span>(<span class="op">~</span><span class="kw">stri_trans_nfkc</span>(.),</span>
<span id="cb12-4"><a href="readexcel.html#cb12-4"></a>              <span class="kw">everything</span>())</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   Species `種 類` `※島の名前` `1クチバシ 長さ(mm)`~ `2クチバシ_大きさ(mm)`~
##   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;                  &lt;dbl&gt;            &lt;dbl&gt;
## 1 Adelie  アデリー~ Torgersen               39.1             18.7
## 2 Adelie  アデリー~ Torgersen               39.5             17.4
## 3 Adelie  アデリー~ Torgersen               40.3             18  
## # ... with 341 more rows, and 4 more variables:
## #   `翼:長さ(mm)` &lt;dbl&gt;, `■体重 単位はg` &lt;dbl&gt;, 女男 &lt;chr&gt;,
## #   `2007~2009` &lt;dbl&gt;</code></pre>
<div style="page-break-after: always;"></div>
</div>
<div id="上記の合わせ技" class="section level4">
<h4><span class="header-section-number">2.1.2.4</span> 上記の合わせ技</h4>
<p><code>%&gt;%</code> でつなぎ合わせて1つの実行で合わせてしまうこともできます。</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="readexcel.html#cb14-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb14-2"><a href="readexcel.html#cb14-2"></a><span class="st">  </span><span class="kw">rename_with</span>(<span class="op">~</span><span class="kw">stri_trans_nfkc</span>(.),</span>
<span id="cb14-3"><a href="readexcel.html#cb14-3"></a>              <span class="kw">everything</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb14-4"><a href="readexcel.html#cb14-4"></a><span class="st">    </span><span class="kw">clean_names</span>(<span class="dt">case =</span> <span class="st">&quot;old_janitor&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   species 種_類 x_島の名前 x1クチバシ_長さ_mm~ x2クチバシ_大きさ_mm~
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;                 &lt;dbl&gt;            &lt;dbl&gt;
## 1 Adelie  アデリー~ Torgersen              39.1             18.7
## 2 Adelie  アデリー~ Torgersen              39.5             17.4
## 3 Adelie  アデリー~ Torgersen              40.3             18  
## # ... with 341 more rows, and 4 more variables:
## #   翼_長さ_mm &lt;dbl&gt;, x_体重_単位はg &lt;dbl&gt;, 女男 &lt;chr&gt;,
## #   x2007_2009 &lt;dbl&gt;</code></pre>
</div>
</div>
<div id="開始行を指定して読み込む" class="section level3">
<h3><span class="header-section-number">2.1.3</span> 開始行を指定して読み込む</h3>
<p>理想的なデータは1行目に列名が入力されている形ですが、最初の数行が空だったり、文字の説明が入っていたりすることも多いです。そうした場合は、以下のような読み込み結果になります。</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="readexcel.html#cb16-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（3行空き）.xlsx&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb16-2"><a href="readexcel.html#cb16-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>) <span class="co"># 紙面の都合のため最初の3列に制限</span></span></code></pre></div>
<pre><code>## # A tibble: 346 x 3
##   ...1    ここに説明とか書いてあるファイル読むのつらいのです~ ...3        
##   &lt;chr&gt;   &lt;chr&gt;                                      &lt;chr&gt;       
## 1 &lt;NA&gt;    &lt;NA&gt;                                       &lt;NA&gt;        
## 2 species island                                     bill_length~
## 3 Adelie  Torgersen                                  39.1        
## # ... with 343 more rows</code></pre>
<p>列名が、セルに内容が入っている行から始まり、他の列名が<code>...1</code>, <code>...3</code>といったものになりました。そしてデータがうまく読み込めていません。これを、指定した行から読み込むには、引数<code>skip =</code>にとばしたい行の数を指定します。</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="readexcel.html#cb18-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（3行空き）.xlsx&quot;</span>, <span class="dt">skip =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   species island bill_length_mm bill_depth_mm flipper_length_~
##   &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;            &lt;dbl&gt;
## 1 Adelie  Torge~           39.1          18.7              181
## 2 Adelie  Torge~           39.5          17.4              186
## 3 Adelie  Torge~           40.3          18                195
## # ... with 341 more rows, and 4 more variables:
## #   body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;, year &lt;dbl&gt;, 種類 &lt;chr&gt;</code></pre>
<p>このように、ちゃんと読む込むことができました。</p>
</div>
<div id="セルを指定して読み込む" class="section level3">
<h3><span class="header-section-number">2.1.4</span> セルを指定して読み込む</h3>
<p>引数<code>range =</code>にセル範囲を指定すれば、そのセル範囲だけを読み込むこともできます。</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="readexcel.html#cb20-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン.xlsx&quot;</span>, <span class="dt">range =</span> <span class="st">&quot;A1:D5&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4 x 4
##   species 種類     island    bill_length_mm
##   &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt;
## 1 Adelie  アデリー Torgersen           39.1
## 2 Adelie  アデリー Torgersen           39.5
## 3 Adelie  アデリー Torgersen           40.3
## 4 Adelie  アデリー Torgersen           NA</code></pre>
<p>他にも、<code>cell_cols =</code>で読みたい列の指定、<code>cell_rows =</code>で読みたい行の指定も行えます。</p>
<p>詳細は、<code>?readxl</code>と打ち込んでヘルプを見るか、readxlの<a href="https://readxl.tidyverse.org/">webサイト</a> <a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a>を参照してください。</p>
</div>
</div>
<div id="シートを指定して読み込む" class="section level2">
<h2><span class="header-section-number">2.2</span> シートを指定して読み込む</h2>
<div id="シート名の確認" class="section level3">
<h3><span class="header-section-number">2.2.1</span> シート名の確認</h3>
<p>複雑なExcelファイルとなると、たくさんのシートが含まれていて、その全容を知るのも一苦労です。Rでは、<code>readxl</code>パッケージの<code>excel_sheets()</code>関数でシート名の一覧を簡単に取得できます。</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="readexcel.html#cb22-1"></a><span class="kw">excel_sheets</span>(<span class="st">&quot;data/ペンギン（シート別）.xlsx&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;アデリー&quot;   &quot;ジェンツー&quot; &quot;ヒゲ&quot;</code></pre>
</div>
<div id="普通の読み込み" class="section level3">
<h3><span class="header-section-number">2.2.2</span> 普通の読み込み</h3>
<p>シートが分かれているExcelファイルをそのまま読みこんでみます。</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="readexcel.html#cb24-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（シート別）.xlsx&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 152 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Adelie  アデリー~ Torge~           39.1          18.7
## 2 Adelie  アデリー~ Torge~           39.5          17.4
## 3 Adelie  アデリー~ Torge~           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
<p>デフォルトでは一番最初のシートのデータが読みこまれます。ここでは、シート「アデリー」が読み込まれました。</p>
</div>
<div id="シートを指定した読み込み" class="section level3">
<h3><span class="header-section-number">2.2.3</span> シートを指定した読み込み</h3>
<p>引数の<code>sheet =</code>にシート名を指定することで読み込めます。</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="readexcel.html#cb26-1"></a><span class="kw">read_excel</span>(<span class="st">&quot;data/ペンギン（シート別）.xlsx&quot;</span>, <span class="dt">sheet =</span> <span class="st">&quot;ジェンツー&quot;</span> )</span></code></pre></div>
<pre><code>## # A tibble: 124 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Gentoo  ジェンツ~ Biscoe           46.1          13.2
## 2 Gentoo  ジェンツ~ Biscoe           50            16.3
## 3 Gentoo  ジェンツ~ Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
</div>
<div id="dflist" class="section level3">
<h3><span class="header-section-number">2.2.4</span> すべてのシートから一気に読み込み</h3>
<p>今まで身につけた知識を使うと、すべてのシートからデータを読みたいときは、単純に</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="readexcel.html#cb28-1"></a>df_Adelie &lt;-<span class="st"> </span></span>
<span id="cb28-2"><a href="readexcel.html#cb28-2"></a><span class="st">  </span><span class="kw">read_excel</span>(<span class="st">&quot;data/ペンギン（シート別）.xlsx&quot;</span>, <span class="dt">sheet =</span> <span class="st">&quot;アデリー&quot;</span> )</span>
<span id="cb28-3"><a href="readexcel.html#cb28-3"></a>df_Gentoo &lt;-<span class="st"> </span></span>
<span id="cb28-4"><a href="readexcel.html#cb28-4"></a><span class="st">  </span><span class="kw">read_excel</span>(<span class="st">&quot;data/ペンギン（シート別）.xlsx&quot;</span>, <span class="dt">sheet =</span> <span class="st">&quot;ジェンツー&quot;</span> )</span>
<span id="cb28-5"><a href="readexcel.html#cb28-5"></a>df_Chinstrap &lt;-<span class="st"> </span></span>
<span id="cb28-6"><a href="readexcel.html#cb28-6"></a><span class="st">  </span><span class="kw">read_excel</span>(<span class="st">&quot;data/ペンギン（シート別）.xlsx&quot;</span>, <span class="dt">sheet =</span> <span class="st">&quot;ヒゲ&quot;</span> )</span></code></pre></div>
<p>と１つずつ読み込めばよいとわかります。しかし、これが100シート分あったら読むだけで多くの時間がかかり、うんざりしてしまうでしょう。また、疲労によりミスも起こるかもしれません。コードも長くて読みにくくなってしまいます。そんな時に<strong>便利で正確で短くコードが書ける</strong>素敵な方法があるのです。おそらくこれを知って使えるようになることが、初心者から中級者への第一歩になるのではないでしょうか。</p>
<p>ここで<strong>一気にレベルが上がり</strong>ますが、これこそがRを使ってExcelファイルを読み込む便利な部分（その用途に限らず、コード書いてコンピュータに働いてもらうの最高！ってなる部分）なので、その魅力をみていきましょう。</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="readexcel.html#cb29-1"></a>path_name &lt;-<span class="st"> &quot;data/ペンギン（シート別）.xlsx&quot;</span> <span class="co"># データのパスを格納</span></span>
<span id="cb29-2"><a href="readexcel.html#cb29-2"></a></span>
<span id="cb29-3"><a href="readexcel.html#cb29-3"></a><span class="co"># シート名を取得しそれぞれから読み込んでリストにまとめる</span></span>
<span id="cb29-4"><a href="readexcel.html#cb29-4"></a>df_list &lt;-</span>
<span id="cb29-5"><a href="readexcel.html#cb29-5"></a><span class="st">  </span><span class="kw">excel_sheets</span>(path_name) <span class="op">%&gt;%</span><span class="st">                     </span></span>
<span id="cb29-6"><a href="readexcel.html#cb29-6"></a><span class="st">  </span><span class="kw">set_names</span>() <span class="op">%&gt;%</span><span class="st">           </span><span class="co"># 名前付きベクトルにする</span></span>
<span id="cb29-7"><a href="readexcel.html#cb29-7"></a><span class="st">  </span><span class="kw">map</span>(read_excel, <span class="dt">path =</span>  path_name)</span>
<span id="cb29-8"><a href="readexcel.html#cb29-8"></a></span>
<span id="cb29-9"><a href="readexcel.html#cb29-9"></a>df_list <span class="co"># 作成したリストの表示</span></span></code></pre></div>
<pre><code>## $アデリー
## # A tibble: 152 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Adelie  アデリー~ Torge~           39.1          18.7
## 2 Adelie  アデリー~ Torge~           39.5          17.4
## 3 Adelie  アデリー~ Torge~           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;
## 
## $ジェンツー
## # A tibble: 124 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Gentoo  ジェンツ~ Biscoe           46.1          13.2
## 2 Gentoo  ジェンツ~ Biscoe           50            16.3
## 3 Gentoo  ジェンツ~ Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;
## 
## $ヒゲ
## # A tibble: 68 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Chinst~ ヒゲ  Dream            46.5          17.9
## 2 Chinst~ ヒゲ  Dream            50            19.5
## 3 Chinst~ ヒゲ  Dream            51.3          19.2
## # ... with 65 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
<p>それぞれのExcelシートから読みこまれた3つのデータ（アデリー、ジェンツー、ヒゲ）はデータフレームとして、<code>df_list</code>にリストと呼ばれる形式にてまとめて格納されています。リストは最初は理解が難しいですが、慣れるとなんでもリストにしたくなるくらい便利なものです。リストの中身を個別に取り出してみてみましょう。</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="readexcel.html#cb31-1"></a>df_list<span class="op">$</span>ジェンツー</span></code></pre></div>
<pre><code>## # A tibble: 124 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Gentoo  ジェンツ~ Biscoe           46.1          13.2
## 2 Gentoo  ジェンツ~ Biscoe           50            16.3
## 3 Gentoo  ジェンツ~ Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
<p>これは、<code>df_list</code>というリストの中の、<code>ジェンツー</code>という要素（ここではデータフレーム）を取り出す、というコードです。<code>$</code>が「（左側にくるオブジェクト）の中の」という意味を表しています。自分でコードを打つと、<code>df_list$</code>と打った時点で、中の要素の一覧が表示されるはずなので、そこからクリックして選ぶこともできます。</p>
<p>それでは、先ほど実行した読み込みコードの解説をします。</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="readexcel.html#cb33-1"></a>path_name &lt;-<span class="st"> &quot;data/ペンギン（シート別）.xlsx&quot;</span></span></code></pre></div>
<p>これは、単にファイルの場所を<code>path_name</code>に格納しただけです。自分のデータで試してみたいときは、基本的にここのパス名を変えるだけで実行できるはずです。</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="readexcel.html#cb34-1"></a>df_list &lt;-</span>
<span id="cb34-2"><a href="readexcel.html#cb34-2"></a><span class="st">  </span><span class="kw">excel_sheets</span>(path_name) <span class="op">%&gt;%</span><span class="st">                    </span></span>
<span id="cb34-3"><a href="readexcel.html#cb34-3"></a><span class="st">  </span><span class="kw">set_names</span>() <span class="op">%&gt;%</span><span class="st">                           </span></span>
<span id="cb34-4"><a href="readexcel.html#cb34-4"></a><span class="st">  </span><span class="kw">map</span>(read_excel, <span class="dt">path =</span>  path_name) </span></code></pre></div>
<p><code>excel_sheets()</code>は上で実行したのと同じです。実行結果はベクトルとして保存されています。<code>set_names()</code>は、ベクトルを名前付きベクトルにする働きをします。なので、ここでできるのは、</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="readexcel.html#cb35-1"></a><span class="kw">excel_sheets</span>(path_name) <span class="op">%&gt;%</span><span class="st">                    </span></span>
<span id="cb35-2"><a href="readexcel.html#cb35-2"></a><span class="st">  </span><span class="kw">set_names</span>()</span></code></pre></div>
<pre><code>##     アデリー   ジェンツー         ヒゲ 
##   &quot;アデリー&quot; &quot;ジェンツー&quot;       &quot;ヒゲ&quot;</code></pre>
<p>です。</p>
<p>それぞれについて<code>purrr</code>パッケージの<code>map()</code>関数を使って<code>read_excel()</code>を1つ1つのシート（ここでは作成した名前付きベクトルの要素）に適用していき、データを読み込みデータフレームにし、1つのリストにまとめるという作業をします。繰り返し似たような作業をするときに、この<code>map()</code>関数が非常に便利です。</p>
<div id="onedflist" class="section level4">
<h4><span class="header-section-number">2.2.4.1</span> 一つのデータフレームにする</h4>
<p><code>bind_rows()</code>は、データフレームを縦に連結します。データフレームがリストになったものが引数にくると、それらをすべて縦につなげてくれます。引数<code>.id =</code>で、リストの要素名を変数の値として入れることができるので、どのデータフレームから来たのか識別することが可能になります。ここでは<code>group</code>という名前にしています。</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="readexcel.html#cb37-1"></a>df_all &lt;-<span class="st"> </span></span>
<span id="cb37-2"><a href="readexcel.html#cb37-2"></a><span class="st">  </span><span class="kw">bind_rows</span>(df_list, <span class="dt">.id =</span> <span class="st">&quot;group&quot;</span>)</span></code></pre></div>
</div>
<div id="作成したデータフレームの確認" class="section level4">
<h4><span class="header-section-number">2.2.4.2</span> 作成したデータフレームの確認</h4>
<p>最初の3行と最後の3行だけを表示してどんなものができたか確認します。<code>dplyr</code>パッケージの<code>slice_head()</code>, <code>slice_tail()</code>関数を使って、引数<code>n =</code>に表示したい行数を指定することで、最初および最後の数行を取得できます。</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="readexcel.html#cb38-1"></a><span class="co"># 最初の3行</span></span>
<span id="cb38-2"><a href="readexcel.html#cb38-2"></a>df_all <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice_head</span>(<span class="dt">n =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 10
##   group species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 アデリー~ Adelie  アデリー~ Torge~           39.1          18.7
## 2 アデリー~ Adelie  アデリー~ Torge~           39.5          17.4
## 3 アデリー~ Adelie  アデリー~ Torge~           40.3          18  
## # ... with 4 more variables: flipper_length_mm &lt;dbl&gt;,
## #   body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;, year &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="readexcel.html#cb40-1"></a><span class="co"># 最後の3行</span></span>
<span id="cb40-2"><a href="readexcel.html#cb40-2"></a>df_all <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice_tail</span>(<span class="dt">n =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 10
##   group species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 ヒゲ  Chinst~ ヒゲ  Dream            49.6          18.2
## 2 ヒゲ  Chinst~ ヒゲ  Dream            50.8          19  
## 3 ヒゲ  Chinst~ ヒゲ  Dream            50.2          18.7
## # ... with 4 more variables: flipper_length_mm &lt;dbl&gt;,
## #   body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;, year &lt;dbl&gt;</code></pre>
<p>一気にやるには<code>slice()</code>関数が便利です。<code>1:3</code>は1行目から3行目、<code>(n()-2):n()</code>は、列数（ただし現在のgroup内）を表す<code>n()</code>とそれから-2行した<code>(n()-2)</code>で表されています。</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="readexcel.html#cb42-1"></a>df_all <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb42-2"><a href="readexcel.html#cb42-2"></a><span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, (<span class="kw">n</span>()<span class="op">-</span><span class="dv">2</span>)<span class="op">:</span><span class="kw">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 6 x 10
##   group species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 アデリー~ Adelie  アデリー~ Torge~           39.1          18.7
## 2 アデリー~ Adelie  アデリー~ Torge~           39.5          17.4
## 3 アデリー~ Adelie  アデリー~ Torge~           40.3          18  
## 4 ヒゲ  Chinst~ ヒゲ  Dream            49.6          18.2
## 5 ヒゲ  Chinst~ ヒゲ  Dream            50.8          19  
## 6 ヒゲ  Chinst~ ヒゲ  Dream            50.2          18.7
## # ... with 4 more variables: flipper_length_mm &lt;dbl&gt;,
## #   body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;, year &lt;dbl&gt;</code></pre>
<div style="page-break-after: always;"></div>
</div>
</div>
</div>
<div id="readseveralexcel" class="section level2">
<h2><span class="header-section-number">2.3</span> 複数のExcelファイルを読み込む</h2>
<p>それでは、さらにRの恩恵を深く実感できる部分に入ります。読みこみたいExcelファイルが大量にある場合です。これも実務上よく遭遇します。やり方としては、<a href="readexcel.html#dflist">2.2.4</a>で使った方法とほぼ同じです。</p>
<p>ただし、ここでは読み込むファイルの構造がすべて同様の場合に限ります。残念ながら、それがかなわない状況に、現実ではたくさん遭遇します。いつか本書の応用編を書くことがあったら、そちらで解説することとして、今回は構造が単純な場合に限って解説します。</p>
<p>おそらく、単純に思いつく方法は、</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="readexcel.html#cb44-1"></a>df_Adelie    &lt;-<span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;data/複数/アデリー.xlsx&quot;</span>)</span>
<span id="cb44-2"><a href="readexcel.html#cb44-2"></a>df_Gentoo    &lt;-<span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;data/複数/ジェンツー.xlsx&quot;</span>)</span>
<span id="cb44-3"><a href="readexcel.html#cb44-3"></a>df_Chinstrap &lt;-<span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;data/複数/ヒゲ.xlsx&quot;</span>)</span></code></pre></div>
<p>と1つずつ読んでいく方法ですが、これも大量にあったら泣きたくなる作業です。1つ1つファイル名を入力やコピペする間にいくらでもミスが生じます。<a href="readexcel.html#hokan">2.1.1.1</a>で紹介した自動補完を使っても、楽しいのは最初だけでしょう。そこで、ファイルを指定するところから極力人の手を介さず進めていく方法を次に解説していきます。</p>
<div id="読み込むファイル名の一覧のオブジェクト作成" class="section level3">
<h3><span class="header-section-number">2.3.1</span> 読み込むファイル名の一覧のオブジェクト作成</h3>
<p>まず、読み込みたいファイルが格納されているフォルダのファイル名、およびパス名の一覧を取得します。</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="readexcel.html#cb45-1"></a>files &lt;-</span>
<span id="cb45-2"><a href="readexcel.html#cb45-2"></a><span class="st">    </span><span class="kw">list.files</span>(<span class="dt">path =</span> <span class="st">&quot;data/複数/&quot;</span>, <span class="dt">full.names =</span> <span class="ot">TRUE</span>)</span>
<span id="cb45-3"><a href="readexcel.html#cb45-3"></a></span>
<span id="cb45-4"><a href="readexcel.html#cb45-4"></a>files</span></code></pre></div>
<pre><code>## [1] &quot;data/複数/アデリー.xlsx&quot;   &quot;data/複数/ジェンツー.xlsx&quot;
## [3] &quot;data/複数/ヒゲ.xlsx&quot;       &quot;data/複数/フォルダ1&quot;      
## [5] &quot;data/複数/フォルダ2&quot;       &quot;data/複数/フォルダ3&quot;</code></pre>
<p><code>list.files()</code>関数は、<code>path =</code>で指定したフォルダ内の情報を取得します。<code>full.names = TRUE</code>でパスも含めます。これをつけないと、ファイル名と拡張子だけの取得になります。</p>
<p>このうち、使用するのはxlsxファイルだけなので、文字列で該当するデータを取得する<code>str_subset()</code>を用い、以下のように限定します。</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="readexcel.html#cb47-1"></a>files &lt;-<span class="st"> </span></span>
<span id="cb47-2"><a href="readexcel.html#cb47-2"></a><span class="st">  </span>files <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">str_subset</span>(<span class="st">&quot;xlsx&quot;</span>)</span>
<span id="cb47-3"><a href="readexcel.html#cb47-3"></a></span>
<span id="cb47-4"><a href="readexcel.html#cb47-4"></a>files</span></code></pre></div>
<pre><code>## [1] &quot;data/複数/アデリー.xlsx&quot;   &quot;data/複数/ジェンツー.xlsx&quot;
## [3] &quot;data/複数/ヒゲ.xlsx&quot;</code></pre>
</div>
<div id="ikkatsuread" class="section level3">
<h3><span class="header-section-number">2.3.2</span> ファイルを一括で読み込む</h3>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="readexcel.html#cb49-1"></a>ldata &lt;-</span>
<span id="cb49-2"><a href="readexcel.html#cb49-2"></a><span class="st">    </span><span class="kw">map</span>(files, <span class="op">~</span><span class="kw">read_xlsx</span>(.))</span>
<span id="cb49-3"><a href="readexcel.html#cb49-3"></a></span>
<span id="cb49-4"><a href="readexcel.html#cb49-4"></a>ldata</span></code></pre></div>
<pre><code>## [[1]]
## # A tibble: 152 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Adelie  アデリー~ Torge~           39.1          18.7
## 2 Adelie  アデリー~ Torge~           39.5          17.4
## 3 Adelie  アデリー~ Torge~           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;
## 
## [[2]]
## # A tibble: 124 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Gentoo  ジェンツ~ Biscoe           46.1          13.2
## 2 Gentoo  ジェンツ~ Biscoe           50            16.3
## 3 Gentoo  ジェンツ~ Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;
## 
## [[3]]
## # A tibble: 68 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Chinst~ ヒゲ  Dream            46.5          17.9
## 2 Chinst~ ヒゲ  Dream            50            19.5
## 3 Chinst~ ヒゲ  Dream            51.3          19.2
## # ... with 65 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
<p>ここでできた<code>ldata</code>は、<a href="readexcel.html#dflist">2.2.4</a>で作成した<code>df_list</code>と同じ構造です。違いはそれぞれのデータフレームの要素名（アデリー、ジェンツー、ヒゲ）が入っていない点です。各要素の上の部分にある名前が<code>[[1]], [[3]], [[3]]</code>と表示されています（つまり、1, 2, 3の数値が割り当てられている）。要素名が入っていないのは不便なので、以下で要素名を改めてつけます。</p>
<div id="ファイル名抽出" class="section level4">
<h4><span class="header-section-number">2.3.2.1</span> ファイル名抽出</h4>
<p>先ほど作成した<code>files</code>から、ファイル名部分だけに加工します。<code>str_replace()</code>は、<code>stringr</code>パッケージの、文字の置換をする関数です。ここでは、拡張子とパス名をそれぞれ<code>""</code>、つまり空白に置換しています。</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="readexcel.html#cb51-1"></a>file_name &lt;-<span class="st"> </span></span>
<span id="cb51-2"><a href="readexcel.html#cb51-2"></a><span class="st">  </span><span class="kw">str_replace</span>(files, <span class="st">&quot;.xlsx&quot;</span>, <span class="st">&quot;&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb51-3"><a href="readexcel.html#cb51-3"></a><span class="st">  </span><span class="kw">str_replace</span>(<span class="st">&quot;data/複数/&quot;</span>, <span class="st">&quot;&quot;</span>)</span>
<span id="cb51-4"><a href="readexcel.html#cb51-4"></a></span>
<span id="cb51-5"><a href="readexcel.html#cb51-5"></a>file_name</span></code></pre></div>
<pre><code>## [1] &quot;アデリー&quot;   &quot;ジェンツー&quot; &quot;ヒゲ&quot;</code></pre>
</div>
<div id="リストの要素名にファイル名を付与" class="section level4">
<h4><span class="header-section-number">2.3.2.2</span> リストの要素名にファイル名を付与</h4>
<p><a href="readexcel.html#dflist">2.2.4</a>で使った<code>set_names()</code>関数は、リストの要素名を付ける時にも使えます。リスト<code>ldata</code>の3つの要素に、<code>file_name</code>の中身を割り当てます。</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="readexcel.html#cb53-1"></a>ldata &lt;-</span>
<span id="cb53-2"><a href="readexcel.html#cb53-2"></a><span class="st">    </span><span class="kw">set_names</span>(ldata, file_name)</span>
<span id="cb53-3"><a href="readexcel.html#cb53-3"></a></span>
<span id="cb53-4"><a href="readexcel.html#cb53-4"></a>ldata</span></code></pre></div>
<pre><code>## $アデリー
## # A tibble: 152 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Adelie  アデリー~ Torge~           39.1          18.7
## 2 Adelie  アデリー~ Torge~           39.5          17.4
## 3 Adelie  アデリー~ Torge~           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;
## 
## $ジェンツー
## # A tibble: 124 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Gentoo  ジェンツ~ Biscoe           46.1          13.2
## 2 Gentoo  ジェンツ~ Biscoe           50            16.3
## 3 Gentoo  ジェンツ~ Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;
## 
## $ヒゲ
## # A tibble: 68 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Chinst~ ヒゲ  Dream            46.5          17.9
## 2 Chinst~ ヒゲ  Dream            50            19.5
## 3 Chinst~ ヒゲ  Dream            51.3          19.2
## # ... with 65 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
<p>このように、ちゃんと要素に名前が付きました。これらを1つのデータフレームにまとめるには、 <a href="readexcel.html#onedflist">2.2.4.1</a>と同じ手順でできます。</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="readexcel.html#cb55-1"></a><span class="kw">bind_rows</span>(ldata, <span class="dt">.id =</span> <span class="st">&quot;group&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="読み込むファイルが複数フォルダにある場合" class="section level3">
<h3><span class="header-section-number">2.3.3</span> 読み込むファイルが複数フォルダにある場合</h3>
<p><code>data/複数</code>フォルダの中に、さらにフォルダ1～フォルダ3がありました。この中にもそれぞれxlsxファイルが入っていて、それぞれ読み込みたいとします。その場合は、先ほど使った<code>list.files()</code>関数の引数、<code>recursive = TRUE</code>を追加します。これによって、フォルダの深い階層までもすべて読み込むことが可能になります。</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="readexcel.html#cb56-1"></a>files &lt;-</span>
<span id="cb56-2"><a href="readexcel.html#cb56-2"></a><span class="st">    </span><span class="kw">list.files</span>(<span class="dt">path =</span> <span class="st">&quot;data/複数/&quot;</span>, <span class="dt">full.names =</span> <span class="ot">TRUE</span>, <span class="dt">recursive =</span> <span class="ot">TRUE</span>)</span>
<span id="cb56-3"><a href="readexcel.html#cb56-3"></a></span>
<span id="cb56-4"><a href="readexcel.html#cb56-4"></a>files</span></code></pre></div>
<pre><code>## [1] &quot;data/複数//フォルダ1/アデリー.xlsx&quot;  
## [2] &quot;data/複数//フォルダ2/ジェンツー.xlsx&quot;
## [3] &quot;data/複数//フォルダ3/ヒゲ.xlsx&quot;      
## [4] &quot;data/複数/アデリー.xlsx&quot;             
## [5] &quot;data/複数/ジェンツー.xlsx&quot;           
## [6] &quot;data/複数/ヒゲ.xlsx&quot;</code></pre>
<p>このうち、使用するのはフォルダ1～3に入っているxlsxファイルだけなので、<code>str_subset()</code>関数で以下のように絞り込みます。ここの<code>""</code>の中に入る文字列がどうなるかが難しいところかもしれませんが、ここは正規表現という本書の範囲を超える世界なので、深入りはしません。</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="readexcel.html#cb58-1"></a>files &lt;-<span class="st"> </span></span>
<span id="cb58-2"><a href="readexcel.html#cb58-2"></a><span class="st">  </span>files <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">str_subset</span>(<span class="st">&quot;フォルダ&quot;</span>)</span></code></pre></div>
<p>あとは<a href="readexcel.html#ikkatsuread">2.3.2</a>と同じ手順で読み込めます。</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="6">
<li id="fn6"><p>以下、まだインストールしていないパッケージがあれば、<code>install.packages("")</code>の<code>""</code>中にパッケージ名を入れて実行するか、RStudioの<code>Packages</code>タブの<code>Install</code>からインストールしてください<a href="readexcel.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago
(Antarctica) penguin data. R package version 0.1.0.
<a href="https://allisonhorst.github.io/palmerpenguins/" class="uri">https://allisonhorst.github.io/palmerpenguins/</a><a href="readexcel.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>ただし、R version 4.0で文字コード関連の挙動が変わったみたいで、R 4.0.2ではエラーになりました…（未解決）<a href="readexcel.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p><a href="https://readxl.tidyverse.org/" class="uri">https://readxl.tidyverse.org/</a><a href="readexcel.html#fnref9" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="project.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="writeexcel.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["excel_r.pdf", "excel_r.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
