<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 一つのexcelファイルを読み込む | Rで読むExcelファイル（仮）</title>
  <meta name="description" content="2 一つのexcelファイルを読み込む | Rで読むExcelファイル（仮）" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="2 一つのexcelファイルを読み込む | Rで読むExcelファイル（仮）" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 一つのexcelファイルを読み込む | Rで読むExcelファイル（仮）" />
  
  
  

<meta name="author" content="やわらかクジラ @matsuchiy" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="project.html"/>
<link rel="next" href="シートを指定して読みこむ.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>はじめに</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#本書の特徴"><i class="fa fa-check"></i>本書の特徴</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#想定読者"><i class="fa fa-check"></i>想定読者</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#本書の構成"><i class="fa fa-check"></i>本書の構成</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#執筆環境"><i class="fa fa-check"></i>執筆環境</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#注意事項など"><i class="fa fa-check"></i>注意事項など</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="project.html"><a href="project.html"><i class="fa fa-check"></i><b>1</b> 前提：プロジェクトの設定</a><ul>
<li class="chapter" data-level="1.1" data-path="project.html"><a href="project.html#どのフォルダのファイルかの指定"><i class="fa fa-check"></i><b>1.1</b> どのフォルダのファイルかの指定</a></li>
<li class="chapter" data-level="1.2" data-path="project.html"><a href="project.html#プロジェクトとは"><i class="fa fa-check"></i><b>1.2</b> プロジェクトとは</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="readoneexcel.html"><a href="readoneexcel.html"><i class="fa fa-check"></i><b>2</b> 一つのexcelファイルを読み込む</a><ul>
<li class="chapter" data-level="2.1" data-path="readoneexcel.html"><a href="readoneexcel.html#最高な機能だよパスの自動補完"><i class="fa fa-check"></i><b>2.1</b> 最高な機能だよ！パスの自動補完</a></li>
<li class="chapter" data-level="2.2" data-path="readoneexcel.html"><a href="readoneexcel.html#列名変数名がひどい場合の読み込み"><i class="fa fa-check"></i><b>2.2</b> 列名（変数名）がひどい場合の読み込み</a><ul>
<li class="chapter" data-level="2.2.1" data-path="readoneexcel.html"><a href="readoneexcel.html#スペースや記号などを自動的に変換してくれる関数できれいに"><i class="fa fa-check"></i><b>2.2.1</b> スペースや記号などを自動的に変換してくれる関数できれいに</a></li>
<li class="chapter" data-level="2.2.2" data-path="readoneexcel.html"><a href="readoneexcel.html#全角半角を自動で"><i class="fa fa-check"></i><b>2.2.2</b> 全角←→半角を自動で</a></li>
<li class="chapter" data-level="2.2.3" data-path="readoneexcel.html"><a href="readoneexcel.html#上記の合わせ技"><i class="fa fa-check"></i><b>2.2.3</b> 上記の合わせ技</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="readoneexcel.html"><a href="readoneexcel.html#開始行を指定して読みこむ"><i class="fa fa-check"></i><b>2.3</b> 開始行を指定して読みこむ</a></li>
<li class="chapter" data-level="2.4" data-path="readoneexcel.html"><a href="readoneexcel.html#セルを指定して読みこむ"><i class="fa fa-check"></i><b>2.4</b> セルを指定して読みこむ</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="シートを指定して読みこむ.html"><a href="シートを指定して読みこむ.html"><i class="fa fa-check"></i><b>3</b> シートを指定して読みこむ</a><ul>
<li class="chapter" data-level="3.1" data-path="シートを指定して読みこむ.html"><a href="シートを指定して読みこむ.html#シート名の確認"><i class="fa fa-check"></i><b>3.1</b> シート名の確認</a></li>
<li class="chapter" data-level="3.2" data-path="シートを指定して読みこむ.html"><a href="シートを指定して読みこむ.html#普通の読み込み"><i class="fa fa-check"></i><b>3.2</b> 普通の読み込み</a></li>
<li class="chapter" data-level="3.3" data-path="シートを指定して読みこむ.html"><a href="シートを指定して読みこむ.html#シートを指定した読み込み"><i class="fa fa-check"></i><b>3.3</b> シートを指定した読み込み</a></li>
<li class="chapter" data-level="3.4" data-path="シートを指定して読みこむ.html"><a href="シートを指定して読みこむ.html#dflist"><i class="fa fa-check"></i><b>3.4</b> すべてのシートから読み込み</a><ul>
<li class="chapter" data-level="3.4.1" data-path="シートを指定して読みこむ.html"><a href="シートを指定して読みこむ.html#onedflist"><i class="fa fa-check"></i><b>3.4.1</b> 一つのデータフレームにする</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="readseveralexcel.html"><a href="readseveralexcel.html"><i class="fa fa-check"></i><b>4</b> 複数のexcelファイルを読み込む</a><ul>
<li class="chapter" data-level="4.1" data-path="readseveralexcel.html"><a href="readseveralexcel.html#読み込むファイル名の一覧のオブジェクト作成"><i class="fa fa-check"></i><b>4.1</b> 読み込むファイル名の一覧のオブジェクト作成</a></li>
<li class="chapter" data-level="4.2" data-path="readseveralexcel.html"><a href="readseveralexcel.html#ファイルを一括で読み込む"><i class="fa fa-check"></i><b>4.2</b> ファイルを一括で読み込む</a><ul>
<li class="chapter" data-level="4.2.1" data-path="readseveralexcel.html"><a href="readseveralexcel.html#ファイル名抽出"><i class="fa fa-check"></i><b>4.2.1</b> ファイル名抽出</a></li>
<li class="chapter" data-level="4.2.2" data-path="readseveralexcel.html"><a href="readseveralexcel.html#リストの要素名にファイル名を付与"><i class="fa fa-check"></i><b>4.2.2</b> リストの要素名にファイル名を付与</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="writeoneexcel.html"><a href="writeoneexcel.html"><i class="fa fa-check"></i><b>5</b> 一つのexcelファイルを保存する</a><ul>
<li class="chapter" data-level="5.1" data-path="writeoneexcel.html"><a href="writeoneexcel.html#groupbymean"><i class="fa fa-check"></i><b>5.1</b> カテゴリ別平均値の作成</a></li>
<li class="chapter" data-level="5.2" data-path="writeoneexcel.html"><a href="writeoneexcel.html#excelファイルの保存"><i class="fa fa-check"></i><b>5.2</b> excelファイルの保存</a><ul>
<li class="chapter" data-level="5.2.1" data-path="writeoneexcel.html"><a href="writeoneexcel.html#ファイル名に自動で本日の日付を入れる"><i class="fa fa-check"></i><b>5.2.1</b> ファイル名に自動で本日の日付を入れる</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="writeseveralexcel.html"><a href="writeseveralexcel.html"><i class="fa fa-check"></i><b>6</b> 複数のファイルを一度に保存する</a><ul>
<li class="chapter" data-level="6.1" data-path="writeseveralexcel.html"><a href="writeseveralexcel.html#splitdf"><i class="fa fa-check"></i><b>6.1</b> データフレームをカテゴリ別に分割する</a></li>
<li class="chapter" data-level="6.2" data-path="writeseveralexcel.html"><a href="writeseveralexcel.html#個別でexcelファイルに保存する"><i class="fa fa-check"></i><b>6.2</b> 個別でExcelファイルに保存する</a><ul>
<li class="chapter" data-level="6.2.1" data-path="writeseveralexcel.html"><a href="writeseveralexcel.html#サンプルデータセット作成コード"><i class="fa fa-check"></i><b>6.2.1</b> サンプルデータセット作成コード</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="writeseveralexcel.html"><a href="writeseveralexcel.html#一ファイルの複数シートに保存する"><i class="fa fa-check"></i><b>6.3</b> 一ファイルの複数シートに保存する</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="readonecsv.html"><a href="readonecsv.html"><i class="fa fa-check"></i><b>7</b> csvファイルの読み込み</a><ul>
<li class="chapter" data-level="7.1" data-path="readonecsv.html"><a href="readonecsv.html#一つのcsvファイルを読み込む"><i class="fa fa-check"></i><b>7.1</b> 一つのcsvファイルを読み込む</a><ul>
<li class="chapter" data-level="7.1.1" data-path="readonecsv.html"><a href="readonecsv.html#utf-8でエンコードされたcsvファイル"><i class="fa fa-check"></i><b>7.1.1</b> UTF-8でエンコードされたcsvファイル</a></li>
<li class="chapter" data-level="7.1.2" data-path="readonecsv.html"><a href="readonecsv.html#文字化けの例shift-jisでエンコードされたcsvファイル"><i class="fa fa-check"></i><b>7.1.2</b> 【文字化けの例】Shift-JISでエンコードされたcsvファイル</a></li>
<li class="chapter" data-level="7.1.3" data-path="readonecsv.html"><a href="readonecsv.html#shift-jisでエンコードされたcsvファイル"><i class="fa fa-check"></i><b>7.1.3</b> Shift-JISでエンコードされたcsvファイル</a></li>
<li class="chapter" data-level="7.1.4" data-path="readonecsv.html"><a href="readonecsv.html#read.csvを使う場合"><i class="fa fa-check"></i><b>7.1.4</b> read.csvを使う場合</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="writeonecsv.html"><a href="writeonecsv.html"><i class="fa fa-check"></i><b>8</b> csvファイルの保存</a><ul>
<li class="chapter" data-level="8.1" data-path="writeonecsv.html"><a href="writeonecsv.html#write_csvを使う"><i class="fa fa-check"></i><b>8.1</b> write_csv()を使う</a><ul>
<li class="chapter" data-level="8.1.1" data-path="writeonecsv.html"><a href="writeonecsv.html#excelで開いても読めるように"><i class="fa fa-check"></i><b>8.1.1</b> Excelで開いても読めるように</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="writeonecsv.html"><a href="writeonecsv.html#write.csvを使う"><i class="fa fa-check"></i><b>8.2</b> write.csv()を使う</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="あとがき.html"><a href="あとがき.html"><i class="fa fa-check"></i>あとがき</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Rで読むExcelファイル（仮）</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="readoneexcel" class="section level1">
<h1><span class="header-section-number">2</span> 一つのexcelファイルを読み込む</h1>
<ul>
<li>excelファイルを読みこむには、<code>readxl</code>パッケージを使います。</li>
<li>dataフォルダ（<code>data/</code>で表現）に入っている「ペンギン.xlsx」を開きます。</li>
<li><code>read_xlsx()</code>関数を使います。したがって、以下すべてファイル形式は<code>.xlsx</code>を想定します。
<ul>
<li><code>read_xls()</code>や<code>read_excel()</code>もあるので、用途によって使い分けられます。ファイル形式が混ざっている時は<code>read_excel()</code>が有用かもしれません。</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="readoneexcel.html#cb1-1"></a><span class="kw">library</span>(readxl)</span>
<span id="cb1-2"><a href="readoneexcel.html#cb1-2"></a></span>
<span id="cb1-3"><a href="readoneexcel.html#cb1-3"></a>df &lt;-<span class="st"> </span></span>
<span id="cb1-4"><a href="readoneexcel.html#cb1-4"></a><span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン.xlsx&quot;</span>) <span class="co"># excelファイルの読み込み</span></span>
<span id="cb1-5"><a href="readoneexcel.html#cb1-5"></a></span>
<span id="cb1-6"><a href="readoneexcel.html#cb1-6"></a>df <span class="co"># データの表示 </span></span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   species 種類  island bill_length_mm bill_depth_mm
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 Adelie  アデリー~ Torge~           39.1          18.7
## 2 Adelie  アデリー~ Torge~           39.5          17.4
## 3 Adelie  アデリー~ Torge~           40.3          18  
## 4 Adelie  アデリー~ Torge~           NA            NA  
## 5 Adelie  アデリー~ Torge~           36.7          19.3
## # ... with 339 more rows, and 4 more variables:
## #   flipper_length_mm &lt;dbl&gt;, body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;,
## #   year &lt;dbl&gt;</code></pre>
<p>上記コードを実行すると、RStudioの右上（デフォルトの配置であれば）のEnvironmentタブに、</p>
<p><code>df  344 obs. of 9 variables</code></p>
<p>という表示が出ると思います。つまり、344行のデータと9列の変数が入っているデータを、オブジェクト<code>df</code>としてRに読みこんだ、ということを示しています。<code>df &lt;-</code>の部分がその作業に該当します。</p>
<p>オブジェクト名である<code>df</code>と打つことで、デフォルトでは最初の10行分のデータが表示されます。ここでは紙面の都合で設定を変えているので5つだけにしています。表示された最初の行にも、<code>A tibble: 344 x 9</code>と、行数x列数の情報が出ています。表示しきれなかった行は、<code>with 339 more rows</code>と省略され、表示しきれなかった列は、<code>body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;, year &lt;dbl&gt;</code>と、名前と<型名>が表示されます。</p>
<p>なお、読みこんだファイルの保存については@ref(write_one_excel)章で解説します。</p>
<div id="最高な機能だよパスの自動補完" class="section level2">
<h2><span class="header-section-number">2.1</span> 最高な機能だよ！パスの自動補完</h2>
<ul>
<li><code>read_xlsx("")</code>と打った後に、<code>" "</code>の中にカーソルを置いて、tabキーを押すと、プロジェクトの中身が一覧で表示されるので、選んでいくだけで目的のファイルがキーボードを打つことなしに選べます！
<ul>
<li>RStudioは<code>" "</code>と打てばどこでもこの補完が可能です</li>
<li>ただし、R version 4.0で文字コード関連の挙動が変わったみたいで、R 4.0.2ではエラーになりました…（未解決）</li>
</ul></li>
<li>上の階層のフォルダに行きたいときは、<code>" "</code>の中に<code>../</code>と打てば可能です。その後にtabキーを押せば上の階層のフォルダが選べます。</li>
</ul>
</div>
<div id="列名変数名がひどい場合の読み込み" class="section level2">
<h2><span class="header-section-number">2.2</span> 列名（変数名）がひどい場合の読み込み</h2>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="readoneexcel.html#cb3-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   Sｐｅｃｉｅｓ `種　類` `※島の名前` `①クチバシ　長さ（ｍｍ）`~
##   &lt;chr&gt;         &lt;chr&gt;    &lt;chr&gt;                  &lt;dbl&gt;
## 1 Adelie        アデリー Torgersen               39.1
## 2 Adelie        アデリー Torgersen               39.5
## 3 Adelie        アデリー Torgersen               40.3
## 4 Adelie        アデリー Torgersen               NA  
## 5 Adelie        アデリー Torgersen               36.7
## # ... with 339 more rows, and 5 more variables:
## #   `②ｸﾁﾊﾞｼ＿大きさ（ｍｍ）` &lt;dbl&gt;, `翼：長さ(mm)` &lt;dbl&gt;,
## #   `■体重　単位はｇ` &lt;dbl&gt;, `&lt;U+329B&gt;&lt;U+329A&gt;` &lt;chr&gt;,
## #   `２００７～２００９` &lt;dbl&gt;</code></pre>
<p>読めることは読めますが、今後のデータ処理を進めるうえで不安が残ります。</p>
<div id="スペースや記号などを自動的に変換してくれる関数できれいに" class="section level3">
<h3><span class="header-section-number">2.2.1</span> スペースや記号などを自動的に変換してくれる関数できれいに</h3>
<p><code>janitor</code>パッケージの<code>clean_names()</code>関数を使って、列名に入り込んでいるスペースや記号などを安全な記号に変換します。</p>
<p>なお、日本語の列名では、引数（ひきすう）に<code>case = "old_janitor"</code>をつけないと読みにくい結果になります。</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="readoneexcel.html#cb5-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb5-2"><a href="readoneexcel.html#cb5-2"></a><span class="kw">library</span>(janitor)</span>
<span id="cb5-3"><a href="readoneexcel.html#cb5-3"></a></span>
<span id="cb5-4"><a href="readoneexcel.html#cb5-4"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb5-5"><a href="readoneexcel.html#cb5-5"></a><span class="st">  </span><span class="kw">clean_names</span>(<span class="dt">case =</span> <span class="st">&quot;old_janitor&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   sｐｅｃｉｅｓ 種_類 x_島の名前 x_クチバシ_長さ_ｍｍ~
##   &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt;                 &lt;dbl&gt;
## 1 Adelie        アデリー~ Torgersen              39.1
## 2 Adelie        アデリー~ Torgersen              39.5
## 3 Adelie        アデリー~ Torgersen              40.3
## 4 Adelie        アデリー~ Torgersen              NA  
## 5 Adelie        アデリー~ Torgersen              36.7
## # ... with 339 more rows, and 5 more variables:
## #   x_ｸﾁﾊﾞｼ_大きさ_ｍｍ &lt;dbl&gt;, 翼_長さ_mm &lt;dbl&gt;,
## #   x_体重_単位はｇ &lt;dbl&gt;, x_u_329b_u_329a &lt;chr&gt;,
## #   ２００７_２００９ &lt;dbl&gt;</code></pre>
<p>さて、ここで使われている <code>%&gt;%</code> は非常に大事なので解説しておきます。</p>
<div id="pipe" class="section level4">
<h4><span class="header-section-number">2.2.1.1</span> %&gt;% とは？</h4>
<p>「パイプ」と読みます。処理を重ねてコードに書いていきたい際に重宝し、現代の<code>tidyverse</code>を使ったRのコードに欠かせないものです。</p>
<p>たとえば、dfのspecies列を選択する、という処理の</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="readoneexcel.html#cb7-1"></a><span class="kw">select</span>(df, species)</span></code></pre></div>
<p>は</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="readoneexcel.html#cb8-1"></a>df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(species)</span></code></pre></div>
<p>と書けます。 <code>%&gt;%</code>の左側にあるものを右側の最初の部分（第1引数）に渡すという働きです。パイプの利点は、いくつもつないで書いていけることです。たとえば、種類別にクチバシの長さの平均値を出したいときには次のようにできます。</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="readoneexcel.html#cb9-1"></a>df <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb9-2"><a href="readoneexcel.html#cb9-2"></a><span class="st">  </span><span class="kw">group_by</span>(species) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb9-3"><a href="readoneexcel.html#cb9-3"></a><span class="st">  </span><span class="kw">summarise</span>(平均値 =<span class="st"> </span><span class="kw">mean</span>(bill_length_mm, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   species   平均値
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Adelie      38.8
## 2 Chinstrap   48.8
## 3 Gentoo      47.5</code></pre>
<p>以下では<code>%&gt;%</code>を多用していきます。</p>
<p>なお、ショートカット<code>ctrl + shit + M</code>（Macだと<code>Cmd + Shift + M</code>）で出せます。</p>
</div>
</div>
<div id="全角半角を自動で" class="section level3">
<h3><span class="header-section-number">2.2.2</span> 全角←→半角を自動で</h3>
<p><code>stringi</code>パッケージの<code>stri_trans_nfkc()</code>関数を使って、変数名で全角-半角のばらつきを統一させます。</p>
<p>ここでは、変数名をリネームするのに<code>dplyr 1.0.0</code>で登場した<code>rename_with()</code>関数を使いました。すべての変数に対し、全角文字を含んでいたら半角に直すというコードになります。</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="readoneexcel.html#cb11-1"></a><span class="kw">library</span>(stringi)</span>
<span id="cb11-2"><a href="readoneexcel.html#cb11-2"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb11-3"><a href="readoneexcel.html#cb11-3"></a><span class="st">  </span><span class="kw">rename_with</span>(<span class="op">~</span><span class="kw">stri_trans_nfkc</span>(.),</span>
<span id="cb11-4"><a href="readoneexcel.html#cb11-4"></a>              <span class="kw">everything</span>())</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   Species `種 類` `※島の名前` `1クチバシ 長さ(mm)`~ `2クチバシ_大きさ(mm)`~
##   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;                  &lt;dbl&gt;            &lt;dbl&gt;
## 1 Adelie  アデリー~ Torgersen               39.1             18.7
## 2 Adelie  アデリー~ Torgersen               39.5             17.4
## 3 Adelie  アデリー~ Torgersen               40.3             18  
## 4 Adelie  アデリー~ Torgersen               NA               NA  
## 5 Adelie  アデリー~ Torgersen               36.7             19.3
## # ... with 339 more rows, and 4 more variables:
## #   `翼:長さ(mm)` &lt;dbl&gt;, `■体重 単位はg` &lt;dbl&gt;, 女男 &lt;chr&gt;,
## #   `2007~2009` &lt;dbl&gt;</code></pre>
</div>
<div id="上記の合わせ技" class="section level3">
<h3><span class="header-section-number">2.2.3</span> 上記の合わせ技</h3>
<p><code>%&gt;%</code> でつなぎ合わせて1つの実行で合わせてしまうこともできます。</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="readoneexcel.html#cb13-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（ひどい列名）ver.xlsx&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-2"><a href="readoneexcel.html#cb13-2"></a><span class="st">  </span><span class="kw">rename_with</span>(<span class="op">~</span><span class="kw">stri_trans_nfkc</span>(.),</span>
<span id="cb13-3"><a href="readoneexcel.html#cb13-3"></a>              <span class="kw">everything</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-4"><a href="readoneexcel.html#cb13-4"></a><span class="st">    </span><span class="kw">clean_names</span>(<span class="dt">case =</span> <span class="st">&quot;old_janitor&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   species 種_類 x_島の名前 x1クチバシ_長さ_mm~ x2クチバシ_大きさ_mm~
##   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;                 &lt;dbl&gt;            &lt;dbl&gt;
## 1 Adelie  アデリー~ Torgersen              39.1             18.7
## 2 Adelie  アデリー~ Torgersen              39.5             17.4
## 3 Adelie  アデリー~ Torgersen              40.3             18  
## 4 Adelie  アデリー~ Torgersen              NA               NA  
## 5 Adelie  アデリー~ Torgersen              36.7             19.3
## # ... with 339 more rows, and 4 more variables:
## #   翼_長さ_mm &lt;dbl&gt;, x_体重_単位はg &lt;dbl&gt;, 女男 &lt;chr&gt;,
## #   x2007_2009 &lt;dbl&gt;</code></pre>
</div>
</div>
<div id="開始行を指定して読みこむ" class="section level2">
<h2><span class="header-section-number">2.3</span> 開始行を指定して読みこむ</h2>
<p>理想的なデータは1行目に列名が入力されている形ですが、最初の数行が空だったり、文字の説明が入っていたりすることも多いです。そうした場合は、以下のような読み込み結果になります。</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="readoneexcel.html#cb15-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（3行空き）.xlsx&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 346 x 9
##   ...1  ここに説明とか書いてあるファイ~ ...3  ...4  ...5  ...6  ...7  ...8 
##   &lt;chr&gt; &lt;chr&gt;            &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 &lt;NA&gt;  &lt;NA&gt;             &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt; 
## 2 spec~ island           bill~ bill~ flip~ body~ sex   year 
## 3 Adel~ Torgersen        39.1  18.7  181   3750  male  2007 
## 4 Adel~ Torgersen        39.5  17.4  186   3800  fema~ 2007 
## 5 Adel~ Torgersen        40.3  18    195   3250  fema~ 2007 
## # ... with 341 more rows, and 1 more variable: ...9 &lt;chr&gt;</code></pre>
<p>列名が、セルに内容が入っている行から始まり、他の列名が<code>...1</code>, <code>...3</code>といったものになりました。</p>
<p>これを、指定した行から読み込むには、引数<code>skip =</code>にとばしたい行の数を指定します。</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="readoneexcel.html#cb17-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン（3行空き）.xlsx&quot;</span>, <span class="dt">skip =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 344 x 9
##   species island bill_length_mm bill_depth_mm flipper_length_~
##   &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;            &lt;dbl&gt;
## 1 Adelie  Torge~           39.1          18.7              181
## 2 Adelie  Torge~           39.5          17.4              186
## 3 Adelie  Torge~           40.3          18                195
## 4 Adelie  Torge~           NA            NA                 NA
## 5 Adelie  Torge~           36.7          19.3              193
## # ... with 339 more rows, and 4 more variables:
## #   body_mass_g &lt;dbl&gt;, sex &lt;chr&gt;, year &lt;dbl&gt;, 種類 &lt;chr&gt;</code></pre>
<p>このように、ちゃんと読むこむことができました。</p>
</div>
<div id="セルを指定して読みこむ" class="section level2">
<h2><span class="header-section-number">2.4</span> セルを指定して読みこむ</h2>
<p>引数<code>range =</code>にセル範囲を指定すれば、そのセル範囲だけを読みこむこともできます。</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="readoneexcel.html#cb19-1"></a><span class="kw">read_xlsx</span>(<span class="st">&quot;data/ペンギン.xlsx&quot;</span>, <span class="dt">range =</span> <span class="st">&quot;A1:D5&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4 x 4
##   species 種類     island    bill_length_mm
##   &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt;
## 1 Adelie  アデリー Torgersen           39.1
## 2 Adelie  アデリー Torgersen           39.5
## 3 Adelie  アデリー Torgersen           40.3
## 4 Adelie  アデリー Torgersen           NA</code></pre>
<p>他にも、<code>cell_cols =</code>で読みたい列の指定、<code>cell_rows =</code>で読みたい行の指定も行えます。</p>
<p>詳細は、<code>?readxl</code>と打ち込んでヘルプを見るか、readxlの<a href="https://readxl.tidyverse.org/">webサイト</a> <a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>を参照してください。</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="4">
<li id="fn4"><p><a href="https://readxl.tidyverse.org/" class="uri">https://readxl.tidyverse.org/</a><a href="readoneexcel.html#fnref4" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="project.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="シートを指定して読みこむ.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["excel_r.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
